import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#0f172a",
        background: "#eef2f9",
        "surface-container": "#e2e8f0",
        "on-surface-variant": "#475569",
        "secondary-container": "#dbeafe",
        "on-tertiary": "#ffffff",
        primary: "#1e3a8a",
        accent: "#2563eb",
        "inverse-surface": "#1e293b",
        "on-tertiary-fixed": "#064e3b",
        "on-tertiary-fixed-variant": "#047857",
        "surface-bright": "#ffffff",
        surface: "#eef2f9",
        "inverse-primary": "#93c5fd",
        "on-secondary-container": "#1e40af",
        "error-container": "#fee2e2",
        "primary-container": "#1d4ed8",
        "on-background": "#0f172a",
        "on-secondary-fixed-variant": "#1e3a8a",
        "primary-fixed": "#dbeafe",
        "surface-variant": "#e2e8f0",
        "tertiary-container": "#065f46",
        "surface-container-low": "#f8fafc",
        "outline-variant": "#cbd5e1",
        "on-primary-fixed-variant": "#1e40af",
        "tertiary-fixed-dim": "#34d399",
        "primary-fixed-dim": "#60a5fa",
        "surface-container-high": "#e2e8f0",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "inverse-on-surface": "#f8fafc",
        error: "#dc2626",
        "on-tertiary-container": "#059669",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#2563eb",
        "surface-dim": "#cbd5e1",
        outline: "#64748b",
        secondary: "#334155",
        "surface-container-highest": "#e2e8f0",
        "on-secondary": "#ffffff",
        "on-error-container": "#991b1b",
        "tertiary-fixed": "#6ee7b7",
        tertiary: "#064e3b",
        "secondary-fixed": "#dbeafe",
        "on-secondary-fixed": "#0f172a",
        "on-primary-fixed": "#1e3a8a",
        "secondary-fixed-dim": "#93c5fd",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.375rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        base: "4px",
        margin: "32px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 1px 2px rgba(15, 23, 42, 0.04), 0 8px 24px rgba(15, 23, 42, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
